export type QueryStatus = "idle" | "loading" | "success" | "error";
export type DataSourceType = "cmts" | "pon" | "legacy_node";

export type DataFreshness = {
  source_type: DataSourceType;
  original_filename: string;
  row_count: number;
  imported_at: string;
  metadata: Record<string, unknown> | null;
};

export type NocAsset = {
  id: string;
  cmts: string | null;
  node: string | null;
  line_code: string | null;
  mac_domain: string | null;
  upstream_port: string | null;
  upstream_connector: string | null;
  downstream_port: string | null;
  power_level: number | null;
  power_level_raw: number | null;
  power_level_imported_at: string | null;
  receiver: string | null;
  return_source: string | null;
  receiver_brand: string | null;
  receiver_rack: string | null;
  sst: string | null;
  hub_max: string | null;
  max_rack: string | null;
  demax_rack: string | null;
  demux_wavelength: string | null;
  dwdm_splitter: string | null;
  edfa: string | null;
  wdm: string | null;
  mux: string | null;
  dcm: string | null;
  demux_a: string | null;
  demux_b: string | null;
  tx_a: string | null;
  tx_channel: string | null;
  tx_a_rack: string | null;
  pre_amp: string | null;
  fiber_down_a: string | null;
  fiber_up_a: string | null;
  tx_b: string | null;
  tx_b_rack: string | null;
  source_row: number | null;
  status: string | null;
  source_file: string | null;
  source_sheet: string | null;
};

export type PonAsset = {
  id: string;
  source_id: string | null;
  headend: string | null;
  olt_frame: string | null;
  olt_card: string | null;
  olt_port_id: string | null;
  pon_no: string | null;
  node: string | null;
  building_id: string | null;
  building_name: string | null;
  building_type: string | null;
  serviceable_units: string | null;
  address_range: string | null;
  building_units: string | null;
  fiber_core_he: string | null;
  olt_port: string | null;
  patch_panel: string | null;
  edfa: string | null;
  notify_date: string | null;
  patch_done_date: string | null;
  pon_done_date: string | null;
  note: string | null;
  extra_note: string | null;
  system_id: string | null;
  edfa_code: string | null;
  only_area: string | null;
  first_splitter: string | null;
  second_splitter: string | null;
  pon_user_type: string | null;
  olt_name: string | null;
  network_code: string | null;
  original_olt: string | null;
  source_row: number | null;
};

export type LegacyNode = {
  id: string;
  source_id: string | null;
  node: string | null;
  cmts: string | null;
  mac_domain: string | null;
  upstream_port: string | null;
  upstream_connector: string | null;
  downstream_port: string | null;
  tx_channel: string | null;
  mux: string | null;
  hub: string | null;
  dcm: string | null;
  return_receiver: string | null;
  demux_a: string | null;
  demux_b: string | null;
  index_channel: string | null;
  source_row: number | null;
  warning: string | null;
};

export type SopAsset = {
  id: string;
  category: "static_ip" | "cm_upgrade" | "optical";
  slug: string;
  title: string;
  caption: string | null;
  sort_order: number;
  content_type: string;
  width: number | null;
  height: number | null;
  image_base64: string;
};
